// сгенерировал mock данные для начала в нейросети(для более правдоподобной информации вместо lorem) 
import type { Project, Task } from "../api/types";

export const mockProjects: Project[] = [
   {
      id: 'proj_001',
      name: 'ЖК "Золотые купола"',
      description: 'Комплекс премиум-класса с подземным паркингом и собственной инфраструктурой. 3 корпуса переменной этажности.',
      photo_url: new URL('../../assets/photo-1.jpg', import.meta.url).href,
      status: 'active',
   },
   {
      id: 'proj_002',
      name: 'БЦ "Технопарк"',
      description: 'Бизнес-центр класса А с конференц-залами, коворкингом и подземной парковкой на 500 мест.',
      photo_url: new URL('../../assets/photo-2.avif', import.meta.url).href,
      status: 'active',
   },
   {
      id: 'proj_003',
      name: 'ТЦ "Мегаполис"',
      description: 'Торгово-развлекательный центр с кинотеатром, фудкортом и детской зоной. Общая площадь 45 000 м².',
      photo_url: new URL('../../assets/photo-3.jpg', import.meta.url).href,
      status: 'paused',
   },
   {
      id: 'proj_004',
      name: 'ЖК "Речной"',
      description: '4 корпуса переменной этажности, набережная, детский сад на территории.',
      photo_url: new URL('../../assets/photo-4.webp', import.meta.url).href,
      status: 'done',
   },
   {
      id: 'proj_005',
      name: 'Складской комплекс "Логистик"',
      description: 'Склад класса А площадью 30 000 м² с ж/д веткой и автомобильными рампами.',
      photo_url: new URL('../../assets/photo-5.webp', import.meta.url).href,
      status: 'canceled',
   },
   {
      id: 'proj_006',
      name: 'Гостиница "Приморская"',
      description: 'Отель 4 звезды на 150 номеров с собственным пляжем и SPA-центром.',
      photo_url: new URL('../../assets/photo-6.webp', import.meta.url).href,
      status: 'active',
   },
   {
      id: 'proj_007',
      name: 'Школа на 1000 мест',
      description: 'Образовательный комплекс с бассейном, спортзалами и современными лабораториями.',
      photo_url: new URL('../../assets/photo-7.jpg', import.meta.url).href,
      status: 'paused',
   },
   {
      id: 'proj_008',
      name: 'Паркинг "Центральный"',
      description: 'Многоуровневый паркинг на 800 машиномест, с электрозарядками и автомойкой.',
      photo_url: new URL('../../assets/photo-8.webp', import.meta.url).href,
      status: 'done',
   },
   {
      id: 'proj_009',
      name: 'Банный комплекс "Парный"',
      description: 'SPA-комплекс с финской сауной, турецким хаммамом и бассейном под открытым небом.',
      photo_url: new URL('../../assets/photo-9.webp', import.meta.url).href,
      status: 'active',
   },
];

export const mockTasks: Task[] = [
   // ===== proj_001 ЖК "Золотые купола" (active) =====
   {
      id: 'task_001',
      name: 'Разработка котлована',
      description: 'Выемка грунта на глубину 8м, устройство песчаной подушки, геодезический контроль',
      startDate: '2024-01-15',
      endDate: '2024-03-20',
      status: 'finish',
      project_id: 'proj_001',
   },
   {
      id: 'task_002',
      name: 'Заливка фундаментной плиты',
      description: 'Монолитная плита толщиной 600мм, армирование двойной сеткой, бетон класса B25',
      startDate: '2024-03-21',
      endDate: '2024-05-10',
      status: 'finish',
      project_id: 'proj_001',
   },
   {
      id: 'task_003',
      name: 'Возведение монолитного каркаса',
      description: 'Колонны, стены, перекрытия. График работ - этаж в 5 дней',
      startDate: '2024-05-11',
      endDate: '2024-09-30',
      status: 'process',
      project_id: 'proj_001',
   },
   {
      id: 'task_004',
      name: 'Фасадные работы',
      description: 'Вентилируемый фасад, утепление 150мм, облицовка керамогранитом',
      startDate: '2024-08-01',
      endDate: '2024-11-30',
      status: 'wait',
      project_id: 'proj_001',
   },
   {
      id: 'task_005',
      name: 'Монтаж лифтового оборудования',
      description: 'Установка 4 лифтов Otis, пусконаладка, получение разрешений',
      startDate: '2024-10-01',
      endDate: '2024-12-15',
      status: 'wait',
      project_id: 'proj_001',
   },
   {
      id: 'task_030',
      name: 'Пусконаладочные работы',
      description: 'Настройка инженерных систем, отопление, вентиляция, электрика. Пробный запуск лифтов.',
      startDate: '2024-12-16',
      endDate: '2025-01-31',
      status: 'wait',
      project_id: 'proj_001',
   },
   {
      id: 'task_031',
      name: 'Благоустройство территории',
      description: 'Устройство парковки, детские площадки, озеленение, установка лавочек и освещения.',
      startDate: '2025-02-01',
      endDate: '2025-03-30',
      status: 'wait',
      project_id: 'proj_001',
   },

   // ===== proj_002 БЦ "Технопарк" (active) =====
   {
      id: 'task_006',
      name: 'Свайные работы',
      description: 'Забивка 500 свай длиной 12м, испытания динамической нагрузкой',
      startDate: '2024-02-01',
      endDate: '2024-03-15',
      status: 'finish',
      project_id: 'proj_002',
   },
   {
      id: 'task_007',
      name: 'Монолитный каркас паркинга',
      description: '2 уровня подземного паркинга, бетонирование стен и колонн',
      startDate: '2024-03-16',
      endDate: '2024-06-15',
      status: 'finish',
      project_id: 'proj_002',
   },
   {
      id: 'task_008',
      name: 'Надземная часть',
      description: 'Колонны, ригели, плиты перекрытия. Бетон B30',
      startDate: '2024-06-16',
      endDate: '2024-10-31',
      status: 'process',
      project_id: 'proj_002',
   },
   {
      id: 'task_009',
      name: 'Фасад и остекление',
      description: 'Витражное остекление, алюмокомпозитные панели',
      startDate: '2024-11-01',
      endDate: '2025-02-28',
      status: 'wait',
      project_id: 'proj_002',
   },

   // ===== proj_003 ТЦ "Мегаполис" (paused) =====
   {
      id: 'task_010',
      name: 'Демонтаж старых конструкций',
      description: 'Снос старых зданий, вывоз строительного мусора',
      startDate: '2024-01-10',
      endDate: '2024-02-28',
      status: 'finish',
      project_id: 'proj_003',
   },
   {
      id: 'task_011',
      name: 'Фундаментная плита',
      description: 'Плита толщиной 800мм, двойное армирование, бетон B30',
      startDate: '2024-03-01',
      endDate: '2024-05-15',
      status: 'process',
      project_id: 'proj_003',
   },
   {
      id: 'task_012',
      name: 'Металлокаркас',
      description: 'Стальные колонны, фермы, связи (приостановлено)',
      startDate: '2024-05-16',
      endDate: '2024-08-30',
      status: 'error',
      project_id: 'proj_003',
   },

   // ===== proj_004 ЖК "Речной" (done) =====
   {
      id: 'task_013',
      name: 'Проектная документация',
      description: 'Разработка ПСД, экспертиза, разрешение',
      startDate: '2023-01-10',
      endDate: '2023-04-25',
      status: 'finish',
      project_id: 'proj_004',
   },
   {
      id: 'task_014',
      name: 'Строительство корпусов',
      description: '4 корпуса по 16 этажей. Монолитно-кирпичная технология',
      startDate: '2023-05-01',
      endDate: '2023-12-20',
      status: 'finish',
      project_id: 'proj_004',
   },
   {
      id: 'task_015',
      name: 'Благоустройство',
      description: 'Детские площадки, парковки, озеленение',
      startDate: '2024-01-15',
      endDate: '2024-03-30',
      status: 'finish',
      project_id: 'proj_004',
   },

   // ===== proj_005 Логистик (canceled) =====
   {
      id: 'task_016',
      name: 'Геологические изыскания',
      description: 'Бурение скважин, анализ грунтов',
      startDate: '2024-01-20',
      endDate: '2024-02-15',
      status: 'finish',
      project_id: 'proj_005',
   },
   {
      id: 'task_017',
      name: 'Проектирование',
      description: 'Разработка КМ, КЖ разделов',
      startDate: '2024-02-16',
      endDate: '2024-05-30',
      status: 'error',
      project_id: 'proj_005',
   },

   // ===== proj_006 Гостиница (active) =====
   {
      id: 'task_018',
      name: 'Котлован и фундамент',
      description: 'Разработка котлована, устройство фундаментной плиты',
      startDate: '2024-03-01',
      endDate: '2024-05-15',
      status: 'finish',
      project_id: 'proj_006',
   },
   {
      id: 'task_019',
      name: 'Монолитный каркас',
      description: 'Возведение 8 этажей монолитного каркаса',
      startDate: '2024-05-16',
      endDate: '2024-09-30',
      status: 'process',
      project_id: 'proj_006',
   },
   {
      id: 'task_020',
      name: 'Внутренняя отделка',
      description: 'Чистовая отделка номеров, холлов, ресторана',
      startDate: '2024-10-01',
      endDate: '2025-02-28',
      status: 'wait',
      project_id: 'proj_006',
   },

   // ===== proj_007 Школа (paused) =====
   {
      id: 'task_021',
      name: 'Подготовка площадки',
      description: 'Выравнивание участка, подведение коммуникаций',
      startDate: '2024-02-01',
      endDate: '2024-04-15',
      status: 'finish',
      project_id: 'proj_007',
   },
   {
      id: 'task_022',
      name: 'Фундамент и каркас',
      description: 'Монолитный каркас здания школы',
      startDate: '2024-04-16',
      endDate: '2024-08-31',
      status: 'process',
      project_id: 'proj_007',
   },
   {
      id: 'task_023',
      name: 'Бассейн',
      description: 'Строительство чаши бассейна, монтаж оборудования',
      startDate: '2024-09-01',
      endDate: '2024-12-20',
      status: 'wait',
      project_id: 'proj_007',
   },

   // ===== proj_008 Паркинг (done) =====
   {
      id: 'task_024',
      name: 'Котлован и фундамент',
      description: 'Глубокий котлован, фундаментная плита',
      startDate: '2023-09-01',
      endDate: '2023-11-15',
      status: 'finish',
      project_id: 'proj_008',
   },
   {
      id: 'task_025',
      name: 'Железобетонный каркас',
      description: 'Монолитные стены и перекрытия 5 уровней',
      startDate: '2023-11-16',
      endDate: '2024-03-31',
      status: 'finish',
      project_id: 'proj_008',
   },
   {
      id: 'task_026',
      name: 'Инженерные системы',
      description: 'Вентиляция, пожаротушение, освещение',
      startDate: '2024-04-01',
      endDate: '2024-06-15',
      status: 'finish',
      project_id: 'proj_008',
   },

   // ===== proj_009 Банный комплекс (active) =====
   {
      id: 'task_027',
      name: 'Нулевой цикл',
      description: 'Фундамент, подземные коммуникации',
      startDate: '2024-04-01',
      endDate: '2024-06-01',
      status: 'finish',
      project_id: 'proj_009',
   },
   {
      id: 'task_028',
      name: 'Основное здание',
      description: 'Возведение бревенчатого сруба и пристроек',
      startDate: '2024-06-02',
      endDate: '2024-10-15',
      status: 'process',
      project_id: 'proj_009',
   },
   {
      id: 'task_029',
      name: 'Бассейн и SPA-зона',
      description: 'Гидроизоляция, плитка, оборудование саун',
      startDate: '2024-10-16',
      endDate: '2025-01-31',
      status: 'wait',
      project_id: 'proj_009',
   },
];